# Generated by Django 5.2.13 on 2026-04-30 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_month', models.PositiveIntegerField()),
                ('payment_year', models.PositiveIntegerField()),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_payments', to='db.enrollment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'enrollment_payment',
            },
        ),
    ]
