# Generated by Django 5.2.13 on 2026-06-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_academic_year_seeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_students', to='db.academicyear'),
        ),
    ]
