# Generated by Django 5.2.13 on 2026-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_student_current_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
