# Generated by Django 5.2.13 on 2026-06-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_payment_month',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_payment_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
