# Generated by Django 5.2.13 on 2026-07-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_remove_enrollment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='db.subject'),
        ),
    ]
