# Generated by Django 5.2.13 on 2026-07-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_courseoffering_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
    ]
