# Generated by Django 5.2.13 on 2026-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_alter_subject_code_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
