# Generated by Django 5.2.13 on 2026-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_video_day_video_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, help_text='School name where the student is currently enrolled', max_length=200, null=True),
        ),
    ]
