# Generated by Django 5.2.13 on 2026-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='level',
            field=models.IntegerField(choices=[(6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12'), (13, 'Grade 13'), (14, 'Grade 14')], unique=True),
        ),
    ]
